# fly.toml configuration for neuralnetworth-backend
app = 'neuralnetworth-backend'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[env]
  PORT = '5001'

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  # WebSocket support
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'

# Health check for the service
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "2s"
